# Generated by Django 4.1.2 on 2022-11-01 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('order_types', models.CharField(max_length=256)),
                ('smart_trade', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('soon', 'soon')], default='soon', max_length=5)),
                ('dca_bot', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('soon', 'soon')], default='soon', max_length=5)),
                ('grid_bot', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('soon', 'soon')], default='soon', max_length=5)),
                ('options_bot', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('soon', 'soon')], default='soon', max_length=5)),
                ('logo', models.ImageField(default='exchange/logo/default.png', upload_to='exchange/logo')),
                ('cover', models.ImageField(default='exchange/cover/default.png', upload_to='exchange/cover')),
            ],
        ),
        migrations.AlterField(
            model_name='exchange',
            name='api_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='api_passphrase',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='api_secret',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exchange.sourceexchange'),
            preserve_default=False,
        ),
    ]
