# Generated by Django 4.1.2 on 2022-11-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_sourceexchange_alter_exchange_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sourceexchange',
            name='order_types',
        ),
        migrations.AddField(
            model_name='sourceexchange',
            name='order_types',
            field=models.ManyToManyField(to='exchange.tradetype'),
        ),
    ]
